#include "main.h"
void GPIO_init__Memory(void){};

void Led_init(void)
{
    RCC_AHB1ENR |= RCC_GPIOB_EN ;
    //PB11 with my macros
    BIT_SET(GPIOB_MODER, GPIO_PIN_OUT_11);
    BIT_SET(GPIOB_OTYPER, GPIO_OFF);
    BIT_SET(GPIOB_OSPEEDR, GPIO_PIN_MED_11);
    BIT_SET(GPIOB_BSRR, GPIO_PIN_RESET_11);
    //PB12 with CMSIS
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE12, (0x1u << GPIO_MODER_MODE12_Pos));
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_12);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED12, (0x1u << GPIO_OSPEEDR_OSPEED12_Pos));
    CLEAR_BIT(GPIOB->BSRR, GPIO_BSRR_BR12);
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD12, (0x0u << GPIO_PUPDR_PUPD12_Pos));
    //PB15 bytes operations
    *(uint32_t *)(0x40020400UL + 0x00UL) |= 0x40000000UL; //MODER
    *(uint32_t *)(0x40020400UL + 0x04UL) |= 0x00; //OTYPER
    *(uint32_t *)(0x40020400UL + 0x08UL) |= 0x40000000UL; //OSPEEDR
    *(uint32_t *)(0x40020400UL + 0x0CUL) |= 0x80000000UL; //BSRR
    //PB13
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE13, (0x1u << GPIO_MODER_MODE13_Pos));
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_13);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED13, (0x1u << GPIO_OSPEEDR_OSPEED13_Pos));
    CLEAR_BIT(GPIOB->BSRR, GPIO_BSRR_BR13);
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD13, (0x0u << GPIO_PUPDR_PUPD13_Pos));
}

void Buttons_Init(void)
{

    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN);
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
    (void)RCC->AHB1ENR;

    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE8_Msk, (0x0u << GPIO_MODER_MODE8_Pos)); // 00 = Input
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD8_Msk, (0x2u << GPIO_PUPDR_PUPD8_Pos)); // 10 = Pull-Down

    MODIFY_REG(GPIOC->MODER, GPIO_MODER_MODE12_Msk, (0x0u << GPIO_MODER_MODE12_Pos)); // 00 = Input
    MODIFY_REG(GPIOC->PUPDR, GPIO_PUPDR_PUPD12_Msk, (0x2u << GPIO_PUPDR_PUPD12_Pos)); // 10 = Pull-Down
    


}

void GPIO_init_led_pb7_blue (void)
{
*(uint32_t *)(0x40023800UL + 0x30UL) |= 0x02UL;
*(uint32_t *)(0x40023800UL + 0x30UL) |= 0x06UL;
*(uint32_t *)(0x40020400UL + 0x00UL) |= 0x4000UL;
*(uint32_t *)(0x40020400UL + 0x04UL) |= 0x00UL;
*(uint32_t *)(0x40020400UL + 0x08UL) |= 0x4000UL;
*(uint32_t *)(0x40020400UL + 0x18UL) |= 0x800000UL;
}
void GPIO_init_led_pb14_red (void)
{
    RCC_AHB1ENR |= RCC_GPIOB_EN | RCC_GPIOC_EN;
    BIT_SET(GPIOB_MODER, GPIO_PIN_OUT_14);
    BIT_SET(GPIOB_OTYPER, GPIO_OFF);
    BIT_SET(GPIOB_OSPEEDR, GPIO_PIN_MED_14);
    BIT_SET(GPIOB_BSRR, GPIO_PIN_RESET_14);
}
void GPIO_init_led_pb0_green (void)
{
//    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN);
//    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE0_0);
//    CLEAR_BIT(GPIOB->OTYPER,GPIO_OTYPER_OT_0);
//    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);
//    SET_BIT(GPIOB->BSRR, GPIO_BSRR_BR0);

   MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE0, (0x1u << GPIO_MODER_MODE0_Pos));
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_0);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED0, (0x1u << GPIO_OSPEEDR_OSPEED0_Pos));
    CLEAR_BIT(GPIOB->BSRR, GPIO_BSRR_BR0);
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD0, (0x0u << GPIO_PUPDR_PUPD0_Pos));
}

// void PB10_out(void)
// {
//     MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE10_Msk, (0x1u << GPIO_MODER_MODE10_Pos)); // Output
//     CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_10); // Push-pull
//     MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED10_Msk, (0x1u << GPIO_OSPEEDR_OSPEED10_Pos)); // Medium
//     MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD10_Msk, (0x00u << GPIO_PUPDR_PUPD10_Pos)); // Off
// }
// void PB10_inp(void)
// {
//     MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE10_Msk, (0x0u << GPIO_MODER_MODE10_Pos)); // 00 = Input
//     MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD10_Msk, (0x2u << GPIO_PUPDR_PUPD10_Pos)); // 10 = Pull-Down
// }
