#include "main.h"
void GPIO_init__Memory(void){};

void Led_init(void)
{
    RCC_AHB1ENR |= RCC_GPIOB_EN ;
    //PB11 with my macros
    BIT_SET(GPIOB_MODER, GPIO_PIN_OUT_11);
    BIT_SET(GPIOB_OTYPER, GPIO_OFF);
    BIT_SET(GPIOB_OSPEEDR, GPIO_PIN_MED_11);
    BIT_SET(GPIOB_BSRR, GPIO_PIN_RESET_11);
    //PB12 with CMSIS
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE12, (0x1u << GPIO_MODER_MODE12_Pos));
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_12);
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED12, (0x1u << GPIO_OSPEEDR_OSPEED12_Pos));
    CLEAR_BIT(GPIOB->BSRR, GPIO_BSRR_BR12);
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD12, (0x0u << GPIO_PUPDR_PUPD12_Pos));
    //PB15 bytes operations
    *(uint32_t *)(0x40020400UL + 0x00UL) |= 0x40000000UL; //MODER
    *(uint32_t *)(0x40020400UL + 0x04UL) |= 0x00; //OTYPER
    *(uint32_t *)(0x40020400UL + 0x08UL) |= 0x40000000UL; //OSPEEDR
    *(uint32_t *)(0x40020400UL + 0x0CUL) |= 0x80000000UL; //BSRR
}

void Buttons_Init(void)
{

    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN);
    (void)RCC->AHB1ENR;

    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE10_Msk, (0x0u << GPIO_MODER_MODE10_Pos)); // 00 = Input
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD10_Msk, (0x2u << GPIO_PUPDR_PUPD10_Pos)); // 10 = Pull-Down


    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE6_Msk, (0x0u << GPIO_MODER_MODE6_Pos)); // 00 = Input
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD6_Msk, (0x2u << GPIO_PUPDR_PUPD6_Pos)); // 10 = Pull-Down
}

void PB10_out(void)
{
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE10_Msk, (0x1u << GPIO_MODER_MODE10_Pos)); // Output
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_10); // Push-pull
    MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED10_Msk, (0x1u << GPIO_OSPEEDR_OSPEED10_Pos)); // Medium
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD10_Msk, (0x00u << GPIO_PUPDR_PUPD10_Pos)); // Off
}
void PB10_inp(void)
{
    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODE10_Msk, (0x0u << GPIO_MODER_MODE10_Pos)); // 00 = Input
    MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPD10_Msk, (0x2u << GPIO_PUPDR_PUPD10_Pos)); // 10 = Pull-Down
}
